version: '3.8'

services:
  rosetta-server:
    build:
      context: .
    volumes:
      - /tmp/rosetta_data/:/data
    ports:
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:8669:8669"
      - "11235:11235"
      - "11235:11235/udp"
    environment:
      - NETWORK=main
      - MODE=online
    restart: unless-stopped 